name: Check

on: [ push, pull_request ]

jobs:
  check_run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, macos-10.15]
        compiler: [gcc, clang]
        build_type: [Debug, Release]
        include:
          - os: ubuntu-18.04
            compiler: gcc
            CC: gcc-7
            CXX: g++-7
          - os: ubuntu-18.04
            compiler: clang
            extra-packages: clang-7 libc++-7-dev libc++abi-7-dev
            CC: clang-7
            CXX: clang++-7
          - os: ubuntu-20.04
            compiler: gcc
            extra-packages: gcc-11 g++-11
            CC: gcc-11
            CXX: g++-11
          - os: ubuntu-20.04
            compiler: clang
            extra-packages: clang-12 libc++-12-dev libc++abi-12-dev
            CC: clang-12
            CXX: clang++-12
          - os: macos-10.15
            compiler: gcc
            CC: gcc-8
            CXX: g++-8
          # macos-10.15's default compiler is Apple Clang 12.0.0, so it doesn't need an 'include' entry

    env:
      CC: ${{ matrix.CC }}
      CXX: ${{ matrix.CXX }}

    steps:
    - name: Install the latest compilers
      if: matrix.extra-packages
      run: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
        sudo add-apt-repository 'deb http://apt.llvm.org/focal/ llvm-toolchain-focal-12 main'
        sudo apt-get update
        sudo apt-get install -y ${{ matrix.extra-packages }}

    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{ matrix.build_type }}

    - name: Unit Tests
      working-directory: ${{github.workspace}}/build
      run: ctest -C Debug

    - name: Run puzzles
      working-directory: ${{github.workspace}}/build
      run: ./puzzles
