#
# Copyright (c) 2022 Emanuel Machado da Silva
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

name: Web Deploy

concurrency: production

on:
  push:
    branches:
      - master
    paths:
      - 'web/**'

jobs:
  build:
    runs-on: ubuntu-20.04

    defaults:
      run:
        working-directory: web

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - run: |
          npm ci
          npm run build

      - uses: actions/upload-artifact@v3
        name: Upload production build directory
        with:
          name: production-build
          path: web/build/

  deploy:
    runs-on: ubuntu-20.04
    needs: build

    environment:
      name: production
      url: https://emanuelmch.github.io/

    steps:
      - name: Download production build from build job
        uses: actions/download-artifact@v3
        with:
          name: production-build

      - uses: cpina/github-action-push-to-another-repository@main
        name: Publish to GH Pages
        env:
          API_TOKEN_GITHUB: ${{ secrets.PAGES_API_TOKEN }}
        with:
          source-directory: .
          destination-github-username: emanuelmch
          destination-repository-name: emanuelmch.github.io
          target-branch: main
